version: "3.9"

services:
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
      target: runner
    container_name: auth-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=supersecret
    depends_on:
      - mongo

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
      target: runner
    container_name: user-service
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - PORT=4002
      - MONGO_URI=mongodb://mongo:27017/user
    depends_on:
      - mongo

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
      target: runner
    container_name: product-service
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=production
      - PORT=4003
      - MONGO_URI=mongodb://mongo:27017/product
    depends_on:
      - mongo
    
   
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ
      - "15672:15672" # Management UI


  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
