# Core
db:
  redis:
    emulate: true
    namespace: EG

plugins:
  jwt-auth-local:
    package: /Users/rajkumarverma/Raj/Work_Interview/scalable-ecommerce-platform/services/gateway-service/dist/plugin

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
